server:
  port: 8080

logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

# ----------------------------------------------------
# ACTUATOR + METRICS + PROMETHEUS CONFIG
# ----------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus    
  endpoint:
    health:
      show-details: always                  # necesario para dashboards de health
  metrics:
    export:
      prometheus:
        enabled: true                       # habilita /actuator/prometheus
